version: "3"
services:
 #############
 ## appium
 ############
 appium:
  container_name: appium
  hostname: appium
  image: appium/appium
  ports:
   - 4723:4723
  volumes:
   - ${PWD}:/dev/bus/usb
   - ${PWD}/log:/var/log/appium.log